### Imports

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("/kaggle/input/datasets/mobeenfatimah/diabetes-risk-prediction-dataset-50k-patients/diabetes_risk_prediction_dataset.csv")

### Understanding the data

In [3]:
df.head()

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk
0,1,32.0,Male,Mexico,182.1,65.8,19.8,71.2,88.4,10.4,...,Yes,No,Good,Retired,Rural,4.4,60,Healthy Diet Plan,Yes,Moderate
1,2,42.0,Other,Saudi Arabia,148.5,101.2,45.9,121.8,247.3,11.3,...,Yes,Yes,Average,Government,Rural,2.1,99,Begin Diabetes Management Plan,Yes,High
2,3,89.0,Other,Argentina,158.1,NaN,37.9,131.8,141.9,6.3,...,Yes,No,Average,Government,Urban,2.8,80,Strict Blood Sugar Monitoring,Yes,High
3,4,87.0,Other,United States,190.9,95.9,26.3,99.1,90.1,7.4,...,No,No,Average,Business,Rural,1.5,82,Begin Diabetes Management Plan,Yes,High
4,5,27.0,Other,Australia,156.9,101.9,41.4,77.1,93.8,12.0,...,Yes,Yes,Poor,Private,Rural,1.6,93,Begin Diabetes Management Plan,Yes,High

In [4]:
df.drop(columns ="Patient_ID",inplace = True)

In [5]:
df.columns

Index(['Age', 'Gender', 'Country', 'Height_cm', 'Weight_kg', 'BMI',
       'Waist_Circumference_cm', 'Blood_Glucose', 'HbA1c',
       'Fasting_Blood_Sugar', 'Insulin_Level', 'Blood_Pressure_Systolic',
       'Blood_Pressure_Diastolic', 'Total_Cholesterol', 'HDL', 'LDL',
       'Triglycerides', 'Heart_Rate', 'Physical_Activity_Level',
       'Exercise_Hours_Per_Week', 'Daily_Walking_Minutes', 'Diet_Quality',
       'Sugar_Intake_Level', 'Sleep_Hours', 'Stress_Level', 'Smoking_Status',
       'Alcohol_Consumption', 'Family_History_Diabetes', 'Hypertension',
       'Heart_Disease', 'Fatty_Liver', 'PCOS', 'Medication_Adherence',
       'Work_Type', 'Residence_Type', 'Daily_Water_Intake_L',
       'Diabetes_Risk_Score', 'AI_Health_Recommendation',
       'Doctor_Consultation_Needed', 'Diabetes_Risk'],
      dtype='object')

In [6]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,Blood_Pressure_Systolic,...,Total_Cholesterol,HDL,LDL,Triglycerides,Heart_Rate,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Sleep_Hours,Daily_Water_Intake_L,Diabetes_Risk_Score
count,49503.000000,47055.000000,47038.000000,50000.000000,50000.000000,49041.000000,48026.000000,50000.000000,50000.000000,50000.000000,...,49000.000000,49000.000000,49000.000000,49000.000000,50000.000000,48008.000000,48036.000000,47983.000000,50000.000000,50000.000000
mean,53.871099,170.018814,87.457003,30.924056,99.960790,159.905245,8.488061,142.607294,23.476724,140.171120,...,220.168635,57.371731,135.014524,229.543259,85.124260,5.017460,89.933442,6.500917,2.998842,74.043920
std,21.130148,14.457787,24.500358,10.290091,23.086579,52.040575,2.313758,44.681799,12.403841,29.168623,...,57.793626,18.720696,49.135613,98.234911,20.390334,2.875922,52.034642,2.027793,1.152273,15.598327
min,18.000000,145.000000,45.000000,11.900000,60.000000,70.000000,4.500000,65.000000,2.000000,90.000000,...,120.000000,25.000000,50.000000,60.000000,50.000000,0.000000,0.000000,3.000000,1.000000,13.000000
25%,35.000000,157.600000,66.300000,22.700000,80.000000,114.700000,6.500000,103.900000,12.800000,115.000000,...,169.800000,41.300000,92.500000,144.700000,68.000000,2.500000,44.900000,4.700000,2.000000,64.000000
50%,54.000000,170.000000,87.300000,30.000000,99.800000,159.900000,8.500000,142.600000,23.400000,140.000000,...,220.400000,57.300000,135.100000,229.500000,85.000000,5.000000,89.800000,6.500000,3.000000,75.000000
75%,72.000000,182.600000,108.600000,37.800000,119.900000,205.100000,10.500000,181.500000,34.300000,165.000000,...,270.500000,73.600000,177.700000,314.600000,103.000000,7.500000,135.200000,8.300000,4.000000,86.000000
max,90.000000,195.000000,130.000000,61.700000,140.000000,250.000000,12.500000,220.000000,45.000000,190.000000,...,320.000000,90.000000,220.000000,400.000000,120.000000,10.000000,180.000000,10.000000,5.000000,100.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         49503 non-null  float64
 1   Gender                      50000 non-null  object
 2   Country                     50000 non-null  object
 3   Height_cm                   47055 non-null  float64
 4   Weight_kg                   47038 non-null  float64
 5   BMI                         50000 non-null  float64
 6   Waist_Circumference_cm      50000 non-null  float64
 7   Blood_Glucose               49041 non-null  float64
 8   HbA1c                       48026 non-null  float64
 9   Fasting_Blood_Sugar         50000 non-null  float64
 10  Insulin_Level               50000 non-null  float64
 11  Blood_Pressure_Systolic     50000 non-null  int64
 12  Blood_Pressure_Diastolic    50000 non-null  int64
 13  Total_Cholesterol           49000 non-null  float64
 14  HDL                         49000 non-null  float64
 15  LDL                         49000 non-null  float64
 16  Triglycerides               49000 non-null  float64
 17  Heart_Rate                  50000 non-null  int64
 18  Physical_Activity_Level     49500 non-null  object
 19  Exercise_Hours_Per_Week     48008 non-null  float64
 20  Daily_Walking_Minutes       48036 non-null  float64
 21  Diet_Quality                50000 non-null  object
 22  Sugar_Intake_Level          50000 non-null  object
 23  Sleep_Hours                 47983 non-null  float64
 24  Stress_Level                50000 non-null  object
 25  Smoking_Status              50000 non-null  object
 26  Alcohol_Consumption         50000 non-null  object
 27  Family_History_Diabetes     50000 non-null  object
 28  Hypertension                50000 non-null  object
 29  Heart_Disease               50000 non-null  object
 30  Fatty_Liver                 50000 non-null  object
 31  PCOS                        50000 non-null  object
 32  Medication_Adherence        49000 non-null  object
 33  Work_Type                   50000 non-null  object
 34  Residence_Type              50000 non-null  object
 35  Daily_Water_Intake_L        50000 non-null  float64
 36  Diabetes_Risk_Score         50000 non-null  int64
 37  AI_Health_Recommendation    50000 non-null  object
 38  Doctor_Consultation_Needed  50000 non-null  object
 39  Diabetes_Risk               50000 non-null  object
dtypes: float64(17), int64(4), object(19)
memory usage: 15.3+ MB

In [8]:
num_cols = df.select_dtypes(include='number').columns.tolist()

num_summary = pd.DataFrame({
    'Mean': df[num_cols].mean(),
    'Std': df[num_cols].std(),
    'Skewness': df[num_cols].skew(),
    'Kurtosis': df[num_cols].kurtosis()
})
print(num_summary)

                                Mean        Std  Skewness  Kurtosis
Age                        53.871099  21.130148  0.007513 -1.206366
Height_cm                 170.018814  14.457787  0.000421 -1.206541
Weight_kg                  87.457003  24.500358  0.004245 -1.191423
BMI                        30.924056  10.290091  0.431769 -0.453116
Waist_Circumference_cm     99.960790  23.086579  0.009688 -1.191417
Blood_Glucose             159.905245  52.040575  0.006298 -1.211848
HbA1c                       8.488061   2.313758  0.001709 -1.203790
Fasting_Blood_Sugar       142.607294  44.681799 -0.001238 -1.199559
Insulin_Level              23.476724  12.403841  0.005540 -1.199893
Blood_Pressure_Systolic   140.171120  29.168623 -0.003759 -1.200772
Blood_Pressure_Diastolic   90.039000  17.575503 -0.009580 -1.193411
Total_Cholesterol         220.168635  57.793626 -0.005053 -1.202765
HDL                        57.371731  18.720696  0.003958 -1.195463
LDL                       135.014524  49.135613 -0.004072 -1.205085
Triglycerides             229.543259  98.234911 -0.000069 -1.199882
Heart_Rate                 85.124260  20.390334 -0.014702 -1.189377
Exercise_Hours_Per_Week     5.017460   2.875922 -0.009297 -1.191545
Daily_Walking_Minutes      89.933442  52.034642  0.004699 -1.206063
Sleep_Hours                 6.500917   2.027793 -0.005071 -1.209712
Daily_Water_Intake_L        2.998842   1.152273  0.003244 -1.189098
Diabetes_Risk_Score        74.043920  15.598327 -0.370847 -0.276348

### Filling missing values and nans

In [9]:
missing_cols = df.isna().sum()[df.isna().sum() > 0]
missing_cols

Age                         497
Height_cm                  2945
Weight_kg                  2962
Blood_Glucose               959
HbA1c                      1974
Total_Cholesterol          1000
HDL                        1000
LDL                        1000
Triglycerides              1000
Physical_Activity_Level     500
Exercise_Hours_Per_Week    1992
Daily_Walking_Minutes      1964
Sleep_Hours                2017
Medication_Adherence       1000
dtype: int64

In [10]:
mean_cols = [
    'Height_cm', 'Weight_kg', 'Sleep_Hours'
]

In [11]:
most_frequent_cols = [
    'Physical_Activity_Level', 'Medication_Adherence'
]

In [12]:
median_cols = [
    'Age', 'Blood_Glucose', 'HbA1c', 'Total_Cholesterol', 
    'HDL', 'LDL', 'Triglycerides', 'Exercise_Hours_Per_Week', 
    'Daily_Walking_Minutes'
]

In [13]:
imputer_transformer = ColumnTransformer(transformers=[
    ('mean_impute', SimpleImputer(strategy='mean'), mean_cols),
    ('median_impute', SimpleImputer(strategy='median'), median_cols),
    ('mode_impute', SimpleImputer(strategy='most_frequent'), most_frequent_cols)
], remainder='passthrough')

In [14]:
all_imputed_cols = mean_cols + median_cols + most_frequent_cols
df[all_imputed_cols] = imputer_transformer.fit_transform(df[all_imputed_cols])

In [15]:
df.isna().sum()[df.isna().sum()>2]

Series([], dtype: int64)