### Imports

In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

### Data Dictionary

In [2]:
data_dict = pd.read_csv("/kaggle/input/datasets/sergionefedov/marriage-longevity-what-makes-relationships-last/data_dictionary.csv")
data_dict

,column,type,description
0,marriage_id,string,Unique marriage id
1,marriage_number,int,"1st, 2nd or 3rd marriage — one of the stronges..."
2,age_at_marriage,int,Age at the start of this marriage
3,age_gap_years,int,Age difference between partners
4,education_level,string,less_than_hs / high_school / some_college / ba...
5,household_income_usd,float,Household income (USD)
6,financial_stress,float,Self-reported financial stress (0-10)
7,both_employed,int,1 if both partners employed
8,cohabited_before,int,1 if the couple cohabited before marrying
9,premarital_counseling,int,1 if they did premarital counselling — a prote...
10,child_before_marriage,int,1 if a child arrived before the marriage
11,n_children,int,Number of children
12,religious_attendance,string,never / rarely / monthly / weekly
13,criticism,float,GOTTMAN behaviour: attacking partner's charact...
14,contempt,float,"GOTTMAN behaviour: mockery, sneering, disgust ..."
15,defensiveness,float,GOTTMAN behaviour: deflecting responsibility (...
16,stonewalling,float,GOTTMAN behaviour: withdrawing and shutting do...
17,repair_attempt_success,float,How well de-escalation attempts land (0-10) — ...
18,positive_negative_ratio,float,Ratio of positive to negative interactions (Go...
19,conflict_frequency_weekly,float,Arguments per week
20,shared_activities_weekly,float,Shared activities per week
21,years_married,float,"Years married (to divorce, or to date if still..."
22,years_to_divorce,float,Years from marriage to divorce (NaN if still m...
23,divorced,int,TARGET: 1 if the marriage ended in divorce

### Dataset

In [3]:
df = pd.read_csv("/kaggle/input/datasets/sergionefedov/marriage-longevity-what-makes-relationships-last/marriage_longevity_master.csv")
df

,marriage_id,marriage_number,age_at_marriage,age_gap_years,education_level,household_income_usd,financial_stress,both_employed,cohabited_before,premarital_counseling,...,contempt,defensiveness,stonewalling,repair_attempt_success,positive_negative_ratio,conflict_frequency_weekly,shared_activities_weekly,years_married,years_to_divorce,divorced
0,MAR000000,1,36,6,less_than_hs,68600.0,5.9,1,1,0,...,7.7,5.8,8.1,4.1,2.22,3.0,4.0,22.0,NaN,0
1,MAR000001,2,59,1,some_college,328800.0,0.0,1,1,0,...,1.7,6.8,3.0,5.1,11.99,1.0,1.0,15.5,NaN,0
2,MAR000002,2,44,1,high_school,139900.0,6.1,0,0,1,...,6.5,4.2,4.8,5.7,2.27,4.0,2.0,7.2,NaN,0
3,MAR000003,1,25,2,bachelors,97600.0,5.9,1,1,1,...,0.0,4.1,0.9,8.7,6.24,0.0,4.0,13.5,NaN,0
4,MAR000004,2,29,3,graduate,98200.0,4.0,0,0,1,...,4.4,4.6,9.6,8.9,2.59,4.0,5.0,7.5,7.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,MAR044995,2,45,3,high_school,145300.0,7.0,1,1,0,...,8.5,7.1,2.1,6.4,3.16,2.0,3.0,1.8,NaN,0
44996,MAR044996,1,33,0,some_college,95600.0,8.9,0,1,0,...,3.9,5.0,8.1,6.7,1.96,4.0,0.0,2.2,NaN,0
44997,MAR044997,1,33,3,some_college,91200.0,4.9,1,0,0,...,1.4,1.5,6.5,7.0,2.33,5.0,0.0,7.8,7.8,1
44998,MAR044998,1,30,5,some_college,21300.0,9.5,0,1,1,...,7.6,4.7,9.1,1.5,4.95,1.0,5.0,9.1,9.1,1
44999,MAR044999,1,33,1,bachelors,51000.0,7.5,0,0,0,...,4.2,6.4,4.4,6.3,1.51,1.0,1.0,40.6,NaN,0

### Different datatypes of different columns

In [4]:
df.dtypes

marriage_id                   object
marriage_number                int64
age_at_marriage                int64
age_gap_years                  int64
education_level               object
household_income_usd         float64
financial_stress             float64
both_employed                  int64
cohabited_before               int64
premarital_counseling          int64
child_before_marriage          int64
n_children                     int64
religious_attendance          object
criticism                    float64
contempt                     float64
defensiveness                float64
stonewalling                 float64
repair_attempt_success       float64
positive_negative_ratio      float64
conflict_frequency_weekly    float64
shared_activities_weekly     float64
years_married                float64
years_to_divorce             float64
divorced                       int64
dtype: object

In [5]:
df.select_dtypes('object').columns

Index(['marriage_id', 'education_level', 'religious_attendance'], dtype='object')

In [6]:
df.select_dtypes('float64').columns

Index(['household_income_usd', 'financial_stress', 'criticism', 'contempt',
       'defensiveness', 'stonewalling', 'repair_attempt_success',
       'positive_negative_ratio', 'conflict_frequency_weekly',
       'shared_activities_weekly', 'years_married', 'years_to_divorce'],
      dtype='object')

In [7]:
df.select_dtypes('int').columns

Index(['marriage_number', 'age_at_marriage', 'age_gap_years', 'both_employed',
       'cohabited_before', 'premarital_counseling', 'child_before_marriage',
       'n_children', 'divorced'],
      dtype='object')

### Summary stats and nan checking

In [8]:
missing_pct = (df.isnull().sum() / len(df)) * 100
print(missing_pct[missing_pct > 0])

years_to_divorce    53.982222
dtype: float64

#### There is noly one column 'years_to_divorce' haviing the nan valus but it is also seen in the DATA_DICT that it is occasional. Hence, ignopring it and continue

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   marriage_id                45000 non-null  object
 1   marriage_number            45000 non-null  int64
 2   age_at_marriage            45000 non-null  int64
 3   age_gap_years              45000 non-null  int64
 4   education_level            45000 non-null  object
 5   household_income_usd       45000 non-null  float64
 6   financial_stress           45000 non-null  float64
 7   both_employed              45000 non-null  int64
 8   cohabited_before           45000 non-null  int64
 9   premarital_counseling      45000 non-null  int64
 10  child_before_marriage      45000 non-null  int64
 11  n_children                 45000 non-null  int64
 12  religious_attendance       45000 non-null  object
 13  criticism                  45000 non-null  float64
 14  contempt                   45000 non-null  float64
 15  defensiveness              45000 non-null  float64
 16  stonewalling               45000 non-null  float64
 17  repair_attempt_success     45000 non-null  float64
 18  positive_negative_ratio    45000 non-null  float64
 19  conflict_frequency_weekly  45000 non-null  float64
 20  shared_activities_weekly   45000 non-null  float64
 21  years_married              45000 non-null  float64
 22  years_to_divorce           20708 non-null  float64
 23  divorced                   45000 non-null  int64
dtypes: float64(12), int64(9), object(3)
memory usage: 8.2+ MB

In [10]:
df.describe()

,marriage_number,age_at_marriage,age_gap_years,household_income_usd,financial_stress,both_employed,cohabited_before,premarital_counseling,child_before_marriage,n_children,...,contempt,defensiveness,stonewalling,repair_attempt_success,positive_negative_ratio,conflict_frequency_weekly,shared_activities_weekly,years_married,years_to_divorce,divorced
count,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,...,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,20708.000000,45000.000000
mean,1.302244,30.168644,2.868156,118024.922222,5.186407,0.658667,0.618178,0.243822,0.189644,1.404733,...,3.256393,4.760267,3.801571,5.628598,4.011752,2.378267,3.035089,10.699487,7.721021,0.460178
std,0.560842,7.588164,2.205134,83738.454555,2.357498,0.474162,0.485839,0.429391,0.392024,1.183376,...,2.181556,2.154957,2.169450,2.284411,2.852853,1.656582,1.920517,7.820057,4.848361,0.498417
min,1.000000,16.000000,0.000000,9000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.500000,0.500000,0.000000
25%,1.000000,25.000000,1.000000,61800.000000,3.600000,0.000000,0.000000,0.000000,0.000000,1.000000,...,1.600000,3.300000,2.200000,4.000000,2.080000,1.000000,2.000000,5.100000,4.200000,0.000000
50%,1.000000,29.000000,2.000000,95700.000000,5.200000,1.000000,1.000000,0.000000,0.000000,1.000000,...,3.200000,4.800000,3.800000,5.700000,3.260000,2.000000,3.000000,8.700000,6.700000,0.000000
75%,2.000000,34.000000,4.000000,148400.000000,6.800000,1.000000,1.000000,0.000000,0.000000,2.000000,...,4.800000,6.200000,5.300000,7.300000,5.060000,3.000000,4.000000,14.000000,10.200000,1.000000
max,3.000000,68.000000,16.000000,600000.000000,10.000000,1.000000,1.000000,1.000000,1.000000,6.000000,...,10.000000,10.000000,10.000000,10.000000,20.000000,12.000000,15.000000,55.000000,45.000000,1.000000

In [11]:
df.shape

(45000, 24)

### Dropping columns

In [12]:
# Droping marriage_id as it is a identical and unique id for every entry
df.drop(columns = 'marriage_id' ,inplace = True)

In [13]:
# Dropping years_to_divorce and years_married (direct target leakage variables) to isolate features known prior to outcome determination.
df.drop(columns = ['years_to_divorce','years_married'],inplace = True)

In [14]:
df.head()

,marriage_number,age_at_marriage,age_gap_years,education_level,household_income_usd,financial_stress,both_employed,cohabited_before,premarital_counseling,child_before_marriage,...,religious_attendance,criticism,contempt,defensiveness,stonewalling,repair_attempt_success,positive_negative_ratio,conflict_frequency_weekly,shared_activities_weekly,divorced
0,1,36,6,less_than_hs,68600.0,5.9,1,1,0,0,...,never,4.8,7.7,5.8,8.1,4.1,2.22,3.0,4.0,0
1,2,59,1,some_college,328800.0,0.0,1,1,0,0,...,never,0.2,1.7,6.8,3.0,5.1,11.99,1.0,1.0,0
2,2,44,1,high_school,139900.0,6.1,0,0,1,0,...,never,5.2,6.5,4.2,4.8,5.7,2.27,4.0,2.0,0
3,1,25,2,bachelors,97600.0,5.9,1,1,1,0,...,rarely,3.7,0.0,4.1,0.9,8.7,6.24,0.0,4.0,0
4,2,29,3,graduate,98200.0,4.0,0,0,1,0,...,rarely,5.4,4.4,4.6,9.6,8.9,2.59,4.0,5.0,1